server:
  port: 8001
  servlet:
    context-path: /demo
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: demo
  profiles:
    active: dev-out
  jackson:
    #?????
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    basic:
      path: /swagger-ui.html
      enabled: true
    user:
      name: admin #账号
      password: 123456  #密码
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?charsetEncoding=UTF-8&serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: root
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
